databases:
  - name: parse_site
    plan: free
    databaseName: parse_site
    user: parse_site

services:
  - type: web
    plan: free
    name: parse_site
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn parse_site.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: parse_site
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
